# Generated by Django 5.2.6 on 2026-01-25 07:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('clave_division', models.CharField(db_column='ClaveDivision', max_length=20, primary_key=True, serialize=False)),
                ('nombre_division', models.CharField(blank=True, db_column='NombreDivision', max_length=80, null=True)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.CharField(db_column='ClaveAsignatura', max_length=20, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(blank=True, db_column='NombreAsignatura', max_length=80, null=True)),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('matricula_ud', models.CharField(blank=True, db_column='MatriculaUD', max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=40, null=True)),
                ('apellido_paterno', models.CharField(blank=True, db_column='ApellidoPaterno', max_length=40, null=True)),
                ('apellido_materno', models.CharField(blank=True, db_column='ApellidoMaterno', max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'usuario_sistema',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('matricula_m', models.CharField(db_column='MatriculaM', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=40, null=True)),
                ('apellido_p', models.CharField(blank=True, db_column='ApellidoP', max_length=84, null=True)),
                ('apellido_m', models.CharField(blank=True, db_column='ApellidoM', max_length=84, null=True)),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'maestro',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes_generados/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporte_historial',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('clave_sala', models.CharField(db_column='ClaveSala', max_length=20, primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(blank=True, db_column='NombreSala', max_length=80, null=True)),
                ('capacidad', models.IntegerField(blank=True, db_column='Capacidad', null=True)),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, db_column='Tema', max_length=80, null=True)),
                ('inicio', models.DateTimeField(db_column='FechaHoraInicio')),
                ('fin', models.DateTimeField(db_column='FechaHoraFin')),
                ('fecha_apartado', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, db_column='ClaveAsignatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.asignatura')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL)),
                ('maestro', models.ForeignKey(blank=True, db_column='MatriculaM', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.maestro')),
                ('sala', models.ForeignKey(blank=True, db_column='ClaveSala', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.sala')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
