# Generated by Django 5.2.6 on 2025-10-25 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('clave_division', models.CharField(db_column='ClaveDivision', max_length=20, primary_key=True, serialize=False)),
                ('nombre_division', models.CharField(blank=True, db_column='NombreDivision', max_length=80, null=True)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.CharField(db_column='ClaveAsignatura', max_length=20, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(blank=True, db_column='NombreAsignatura', max_length=80, null=True)),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('matricula_m', models.CharField(db_column='MatriculaM', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=40, null=True)),
                ('apellido_p', models.CharField(blank=True, db_column='ApellidoP', max_length=84, null=True)),
                ('apellido_m', models.CharField(blank=True, db_column='ApellidoM', max_length=84, null=True)),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'maestro',
            },
        ),
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('matricula_ud', models.CharField(db_column='MatriculaUD', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=40, null=True)),
                ('apellido_p', models.CharField(blank=True, db_column='ApellidoP', max_length=84, null=True)),
                ('apellido_m', models.CharField(blank=True, db_column='ApellidoM', max_length=84, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=80, null=True)),
                ('division', models.ForeignKey(db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administradorsalas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('clave_sala', models.CharField(db_column='ClaveSala', max_length=20, primary_key=True, serialize=False)),
                ('nombre_sala', models.CharField(blank=True, db_column='NombreSala', max_length=80, null=True)),
                ('division', models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
    ]
