# Generated by Django 5.2.6 on 2025-10-25 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, db_column='Tema', max_length=80, null=True)),
                ('inicio', models.DateTimeField(db_column='FechaHoraInicio')),
                ('fin', models.DateTimeField(db_column='FechaHoraFin')),
                ('fecha_apartado', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, db_column='ClaveAsignatura', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.asignatura')),
                ('maestro', models.ForeignKey(blank=True, db_column='MatriculaM', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.maestro')),
                ('sala', models.ForeignKey(blank=True, db_column='ClaveSala', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.sala')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
