# Generated by Django 5.2.6 on 2025-09-27 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('matricula_ud', models.CharField(db_column='MatriculaUD', max_length=20, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('division', models.ForeignKey(db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administradorsalas',
            },
        ),
    ]
