# Generated by Django 5.2.6 on 2026-01-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_generacion']},
        ),
        migrations.AddField(
            model_name='reporte',
            name='division',
            field=models.ForeignKey(default='CACYTY2023', on_delete=django.db.models.deletion.CASCADE, to='reservas.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_fin_datos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_inicio_datos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('OCUPACION', 'Ocupación por Sala'), ('DOCENTE', 'Actividad por Maestro'), ('GENERAL', 'Resumen General Mensual')], default='GENERAL', max_length=20),
        ),
    ]
