# Generated by Django 5.2.6 on 2026-01-30 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reporte_options_reporte_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestro',
            name='usuario',
            field=models.OneToOneField(blank=True, db_column='Usuario_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_maestro', to=settings.AUTH_USER_MODEL),
        ),
    ]
