# Generated by Django 5.2.6 on 2026-02-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_maestro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='division',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='matricula_ud',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='maestro',
            name='telefono',
            field=models.CharField(blank=True, db_column='Telefono', max_length=20, null=True),
        ),
    ]
