# Generated by Django 6.0.2 on 2026-05-18 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_remove_usuario_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(db_column='NombreActividad', max_length=50, unique=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='requerimientos',
            field=models.TextField(blank=True, db_column='Requerimientos', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='actividad',
            field=models.ForeignKey(db_column='Actividad_ID', default=1, on_delete=django.db.models.deletion.PROTECT, to='reservas.actividad'),
            preserve_default=False,
        ),
    ]
