# Generated by Django 6.0.2 on 2026-05-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_actividad_reserva_requerimientos_reserva_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'División', 'verbose_name_plural': 'Divisiones'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.RemoveField(
            model_name='sala',
            name='division',
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edificio', models.CharField(db_column='NombreEdificio', max_length=50)),
                ('division', models.ForeignKey(db_column='ClaveDivision', on_delete=django.db.models.deletion.CASCADE, to='reservas.division')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'edificio',
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='edificio',
            field=models.ForeignKey(blank=True, db_column='IdEdificio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.edificio'),
        ),
        migrations.AddConstraint(
            model_name='edificio',
            constraint=models.UniqueConstraint(fields=('nombre_edificio', 'division'), name='unique_edificio_por_division'),
        ),
    ]
