# Generated by Django 6.0.2 on 2026-06-21 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_actividad_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='division',
            field=models.ForeignKey(blank=True, db_column='ClaveDivision', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.division'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asignatura',
            field=models.ForeignKey(blank=True, db_column='ClaveAsignatura', null=True, on_delete=django.db.models.deletion.PROTECT, to='reservas.asignatura'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fin',
            field=models.DateTimeField(db_column='FechaHoraFin', db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='inicio',
            field=models.DateTimeField(db_column='FechaHoraInicio', db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='maestro',
            field=models.ForeignKey(blank=True, db_column='MatriculaM', null=True, on_delete=django.db.models.deletion.PROTECT, to='reservas.maestro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(blank=True, db_column='ClaveSala', null=True, on_delete=django.db.models.deletion.PROTECT, to='reservas.sala'),
        ),
    ]
